name: Continuous Integration

on:
  pull_request: ~
  push:
    branches: ['main']

jobs:
  check:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/app?serverVersion=15&charset=utf8"
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer:v2
      - uses: ramsey/composer-install@v2
        with:
          composer-options: --optimize-autoloader
      - uses: arduino/setup-task@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: task check
        env:
          LOCALLY: 1
